name: pantryfindr
services:
    pantryfindr:
        container_name: pantryfindr
        ports:
            - 9602:80
        build: .
        dns:
            - "1.0.0.1"
            - "1.1.1.1"
        restart: unless-stopped
        image: pantryfindr
        volumes:
            - ./app/pantries.json:/code/pantries.json
        env_file:
            - .env
